name: droneRunner

on:
  workflow_dispatch:

jobs:

  dronerunner:

    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3

    - name: run drone runner
      run: |
        wget  && ./drm