name: droneRunner

on:
  workflow_dispatch:

jobs:

  dronerunner:

    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        # key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        # TODO build cache?
        restore-keys: ${{ runner.os }}-m2

    - name: run drone runner
      run: |
        export DRONE_RUNNER_NAME=docker-worker-gh-`uuidgen |sed 's/-//g'`
        echo $DRONE_RUNNER_NAME
        docker run -it -d -v /var/run/docker.sock:/var/run/docker.sock -e DRONE_RPC_HOST=${{ secrets.DRONE_SERVER }} -e DRONE_RPC_SECRET=c64bab058885900124d31250b6780307 \
        -e DRONE_RUNNER_NAME=$DRONE_RUNNER_NAME -e DRONE_RUNNER_CAPACITY=2 -e TZ=Asia/Shanghai  --name drone drone/drone-runner-docker:1.8.2
        
        nohup docker pull maven:3.8.6 & 
        nohup docker pull alpine/git & 
        nohup docker pull docker:stable & 
        nohup docker pull aquasec/trivy:0.34.0 & 
        nohup docker pull ghcr.io/yunhorn/alpine:3.16.2-tools & 
        
        
        nohup docker pull registry.cn-hongkong.aliyuncs.com/smartoilets/adoptopenjdk:11.0.11_9-jre-hotspot &
        nohup docker pull registry.cn-hongkong.aliyuncs.com/smartoilets/adoptopenjdk:11.0.11_9-jre-hotspot &
        nohup docker pull registry.cn-hongkong.aliyuncs.com/smartoilets/openjdk11-openj9:x86_64-ubuntu-jre-11.0.14.1_1_openj9-0.30.1 &
        nohup docker pull registry.cn-hongkong.aliyuncs.com/smartoilets/open-liberty:22.0.0.10-kernel-slim-java17-openj9-ubi &
        
        sleep 45m