# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RepoJob

on:
  push:
    branches:
      - "main"
  schedule:
    # - cron: '0/10 * * * *'
    - cron: '0/20 * * * *'
    # - cron: '0 * * * *' 
    # - cron: '10 * * * *'
    # - cron: '20 * * * *'
    - cron: '30 * * * *'
    # - cron: '40 * * * *'

jobs:

  repojob:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run repojob
      run: |
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -e OWNER=yunhorn -e REPO=smartoilets --rm ghcr.io/yunhorn/repojob:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -e OWNER=yunhorn -e REPO=fe-sdk --rm ghcr.io/yunhorn/repojob:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -e OWNER=yunhorn -e REPO=projectsmartoilets --rm ghcr.io/yunhorn/repojob:latest