# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RepoJob

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "main"
  schedule:
    # - cron: '0/10 * * * *'
    - cron: '0/20 * * * *'
    # - cron: '0 * * * *' 
    # - cron: '10 * * * *'
    # - cron: '20 * * * *'
    - cron: '30 * * * *'
    # - cron: '40 * * * *'




jobs:

  repojob:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

        # docker build -t ghcr.io/yunhorn/repojobdata:latest .
        # docker push ghcr.io/yunhorn/repojobdata:latest

    - name: run repojob
      run: |
        docker login ghcr.io -u yunhorn-bot -p ${{ secrets.GITHUB_TOKEN }}
        docker run -v $PWD/data:/data --rm ghcr.io/yunhorn/repojobdata:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -v $PWD/data:/data -e OWNER=yunhorn -e REPO=smartoilets --rm ghcr.io/yunhorn/repojob:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -v $PWD/data:/data -e OWNER=yunhorn -e REPO=smartoilets-front --rm ghcr.io/yunhorn/repojob:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -v $PWD/data:/data -e OWNER=yunhorn -e REPO=repojob --rm ghcr.io/yunhorn/repojob:latest
        docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} -v $PWD/data:/data -e OWNER=yunhorn -e REPO=watchdog --rm ghcr.io/yunhorn/repojob:latest
        docker logout ghcr.io
        